---
- name: Setup ubuntu 22.04 box
  hosts: default
  become: true
  vars_files: vars.yaml
  tasks:
    - name: "Install apt packages: {{ apt_packages | join(', ') }}"
      when: apt_packages | length > 0
      ansible.builtin.apt:
        cache_valid_time: 3600
        name: "{{ apt_packages }}"

    - name: Set timezone to '{{ timezone }}'
      community.general.timezone:
        name: "{{ timezone }}"
        hwclock: local

    - name: Ensure locale '{{ locale }}'
      community.general.locale_gen:
        name: "{{ locale }}"

    - name: Set LANG and LC_ALL to '{{ locale }}'
      loop:
        - LANG
        - LC_ALL
      ansible.builtin.lineinfile:
        path: /etc/default/locale
        regexp: "^{{ item }}="
        line: "{{ item }}={{ locale }}"

    - name: Set keyboard layout to '{{ keyboard_layout }}'
      ansible.builtin.lineinfile:
        path: /etc/default/keyboard
        regexp: "^XKBLAYOUT="
        line: XKBLAYOUT="{{ keyboard_layout }}"

    - name: Disable swap
      ansible.builtin.lineinfile:
        state: absent
        path: /etc/fstab
        regexp: "^/swap"

    - name: "Install snap_packages: {{ snap_packages | join(', ') }}"
      when: snap_packages | length > 0
      with_items: "{{ snap_packages }}"
      community.general.snap:
        name: "{{ item.name }}"
        channel: "{{ item.channel }}"
        classic: "{{ item.classic }}"

    - name: Customize gnome daemon conf
      with_items:
        - { key: "AutomaticLogin", value: vagrant }
        - { key: "AutomaticLoginEnable", value: true }
      ansible.builtin.lineinfile:
        path: /etc/gdm3/custom.conf
        insertafter: "^\\[daemon\\]"
        line: "{{ item.key }}={{ item.value }}"

    - name: Ensure dconf user profile
      tags: skip_ansible_lint
      ansible.builtin.blockinfile:
        path: /etc/dconf/profile/user
        create: true
        block: |
          user-db:user
          system-db:local

    - name: Custmize gnome background image
      tags: skip_ansible_lint
      ansible.builtin.blockinfile:
        path: /etc/dconf/db/local.d/00-background
        create: true
        block: |
          [org/gnome/desktop/background]
          picture-uri='file:///usr/share/backgrounds/jj_dark_by_Hiking93.jpg'

    - name: Create lockfile for gnome background image
      tags: skip_ansible_lint
      ansible.builtin.blockinfile:
        path: /etc/dconf/db/local.d/locks/background
        create: true
        block: |
          /org/gnome/desktop/background/picture-uri

    - name: Reload dconf
      ansible.builtin.command: dconf update

    - name: Reboot box
      ansible.builtin.reboot:
