Vagrant.configure("2") do |config|
  # vagrant confs
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202404.23.0"
  config.vm.box_check_update = false

  # virtualbox provider confs
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  # ansible provisioner confs
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
